create table "public"."payment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "mail_id" text not null,
    "amount" bigint,
    "payment_datetime" timestamp without time zone
);


alter table "public"."payment" enable row level security;

CREATE UNIQUE INDEX payment_mail_id_key ON public.payment USING btree (mail_id);

CREATE UNIQUE INDEX payment_pkey ON public.payment USING btree (id);

alter table "public"."payment" add constraint "payment_pkey" PRIMARY KEY using index "payment_pkey";

alter table "public"."payment" add constraint "payment_mail_id_key" UNIQUE using index "payment_mail_id_key";

grant delete on table "public"."payment" to "anon";

grant insert on table "public"."payment" to "anon";

grant references on table "public"."payment" to "anon";

grant select on table "public"."payment" to "anon";

grant trigger on table "public"."payment" to "anon";

grant truncate on table "public"."payment" to "anon";

grant update on table "public"."payment" to "anon";

grant delete on table "public"."payment" to "authenticated";

grant insert on table "public"."payment" to "authenticated";

grant references on table "public"."payment" to "authenticated";

grant select on table "public"."payment" to "authenticated";

grant trigger on table "public"."payment" to "authenticated";

grant truncate on table "public"."payment" to "authenticated";

grant update on table "public"."payment" to "authenticated";

grant delete on table "public"."payment" to "service_role";

grant insert on table "public"."payment" to "service_role";

grant references on table "public"."payment" to "service_role";

grant select on table "public"."payment" to "service_role";

grant trigger on table "public"."payment" to "service_role";

grant truncate on table "public"."payment" to "service_role";

grant update on table "public"."payment" to "service_role";


